language: r
os: linux
cache: packages
dist: trusty

r_binary_packages:
  - covr

jobs:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true

r_check_args: "--as-cran --no-build-vignettes --no-manual"

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: never
    on_failure: never
